name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - name: Use repo content
      uses: actions/checkout@main
      with:
        submodules: true
    - name: Install dependencies
      run: sudo apt install -y libpthread-stubs0-dev libjansson-dev
    - name: make
      run: make bulkdns
