name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - name: Use repo content
      uses: actions/checkout@main
    - name: make
      run: make bulkdns
